- hosts: k8-cluster-master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: k8-cluster-1:k8-cluster-2
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['k8-cluster-master'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt